Safe script path
pyiron/pyiron_base pull request #118
Opened 2020-12-14 21:57 UTC by samwaseda

Raised [here](https://github.com/pyiron/pyiron/issues/1261)

2020-12-15 10:24 UTC, pmrv commented
This is not a specific issue with this PR, but in some of our `validate_ready_to_run` we raise `ValueError` and in some we raise `AssertionError`.  I'm not really partial either way, but I think we should agree on one type of exception to run or specify the semantics when to raise which.

2020-12-15 10:54 UTC, samwaseda commented
According to [python doc](https://docs.python.org/3/library/exceptions.html):

- `ValueError`: Raised when an operation or function receives an argument that has the right type but an inappropriate value, and the situation is not described by a more precise exception such as IndexError.
- `AssertionError`: Raised when an assert statement fails.

Since in this case nothing got an argument (let alone the right type), I would claim `ValueError` is not the right error. I'm gladly overruled if you disagree.

2020-12-15 11:25 UTC, liamhuber commented
If you expect a path and get `None`, I think `TypeError` is best.

2020-12-15 11:41 UTC, samwaseda commented
> If you expect a path and get `None`, I think `TypeError` is best.

I'm also fine with `TypeError`, but that sounds to me like the user actively put a wrong type, while in reality it's from developers' perspective that not setting the script path results in a different type than `str`.

A slightly different question: Would there be a practical problem if we set a potentially disputable warning (other than the fact that it could be misleading for the user)?

2020-12-15 11:48 UTC, liamhuber commented
> I'm also fine with `TypeError`, but that sounds to me like the user actively put a wrong type, while in reality it's from developers' perspective that not setting the script path results in a different type than `str`.

`TypeError: ScriptJob.input.script_path expects a path but got None. Please provide a path before running.`

Anyone who reads this will understand why it's a `TypeError`, and the people who still don't get it, frankly, are probably not the type of people who read stack traces to begin with 😝 

> A slightly different question: Would there be a practical problem if we set a potentially disputable warning (other than the fact that it could be misleading for the user)?

Let's rather be technically correct -- the best type of correct there is 😉

2020-12-15 12:32 UTC, samwaseda commented
Speaking of the distinction between `ValueError` and `TypeError`, there's quite a lot of work to be done, because as far as I know we mostly use `ValueError`, e.g. [here](https://github.com/pyiron/pyiron/blob/master/pyiron/atomistics/structure/atoms.py#L157), [here](https://github.com/pyiron/pyiron/blob/master/pyiron/atomistics/structure/atoms.py#L257), [here](https://github.com/pyiron/pyiron/blob/master/pyiron/atomistics/structure/atoms.py#L635), [here](https://github.com/pyiron/pyiron/blob/master/pyiron/atomistics/structure/atoms.py#L2336) or [here](https://github.com/pyiron/pyiron/blob/master/pyiron/atomistics/structure/atoms.py#L2392) (and I'm only naming those found in `atoms.py`)

2020-12-15 16:12 UTC, liamhuber commented
Yeah, valid point. But this is definitely a niche enough issue that I'm content to "start doing it right now" rather than worry about perfect adherence throughout the codebase

2020-12-15 20:16 UTC, liamhuber requested changes
Please fix the codacy "unused" complaint. Fixing the duplication complaint seems like overkill though -- IMO it's just fine to duplicate code *once*.

2020-12-15 20:16 UTC, liamhuber commented on tests/job/test_script.py
> +        file_location = os.path.dirname(os.path.abspath(__file__))
Codacy appears correct to complain about this, indeed it doesn't appear to be used.

2020-12-16 07:25 UTC, liamhuber approved these changes

2020-12-16 07:25 UTC, merged