Fix multi dimensional arrays with FlattenedStorage.to_pandas
pyiron/pyiron_base pull request #1335
Opened 2024-02-14 14:04 UTC by pmrv

2024-02-14 14:06 UTC, jan-janssen requested changes
To guarantee the stability of these kinds of conversions it would be great to add tests.

2024-07-16 16:07 UTC, jan-janssen commented
@pmrv Can you merge `main` into your branch? Especially as the directory structure for the tests changed?

2024-07-16 20:17 UTC, pmrv commented
> @pmrv Can you merge `main` into your branch? Especially as the directory structure for the tests changed?

Should be fixed now.

2024-07-16 20:27 UTC, jan-janssen commented on pyiron_base/_tests.py
> +    def _assert_equal_numpy(self, a, b, msg=""):
Is this necessary? I thought with the changes in line 48 now `None` is supported and maybe the better choice.

2024-07-16 20:33 UTC, jan-janssen commented on tests/unit/storage/test_flattenedstorage.py
> +            )
I am a bit confused about the `try except` part. I agree that it gives a nicer error message but at the same time it is not as readable.

2024-07-16 21:25 UTC, pmrv commented on pyiron_base/_tests.py
> +    def _assert_equal_numpy(self, a, b, msg=""):
```suggestion
    def _assert_equal_numpy(self, a, b, msg=None):
```

2024-07-17 03:44 UTC, jan-janssen approved these changes
Looks good to me

2024-07-17 08:34 UTC, merged