Fix copy to
pyiron/pyiron_base pull request #80
Opened 2020-11-16 13:51 UTC by sudarsan-surendralal

Debugging the `copy_to` function to load the already existing job with the same name. This is necessary for many workflows (including the ones in the recent phase diagrams workshop) to work seamlessly.

2020-11-16 13:56 UTC, jan-janssen commented on pyiron_base/job/generic.py
> +            if new_job_name in job_table.job.tolist():
```suggestion
        if len(job_table) > 0 and new_job_name in job_table.job.values:
```

2020-11-16 13:57 UTC, jan-janssen commented on pyiron_base/job/generic.py
> +                return project[new_job_name]
```suggestion
                return project.load(new_job_name)
```
To be a bit more explicit.

2020-11-16 13:58 UTC, jan-janssen commented
It would be great to add a test for this functionality as it is at the core of pyiron and we only have a very limited number of tests for `pyiron_base` so far.

2020-11-16 14:28 UTC, jan-janssen commented on pyiron_base/job/generic.py
> +                return project.load(new_job_name)
```suggestion
    return project.load(new_job_name)
```

2020-11-16 19:12 UTC, liamhuber requested changes
It would be nice to have something like the `delete_existing_job` that exists for `create_job`, so that you can overwrite instead of loading. I'm sure, but I think this should be as easy as putting the old code and the new code (516+517 here) inside an `if/else` clause based on the input flag?

Other than that feature request, I'm happy. Great to see more tests!

2020-11-17 15:27 UTC, jan-janssen commented on pyiron_base/job/generic.py
> +                print("checkpoint 2")
```suggestion
```

2020-11-17 15:27 UTC, jan-janssen commented on pyiron_base/job/generic.py
> +            print("checkpoint 1", delete_existing_job)
```suggestion
```

2020-11-17 15:49 UTC, jan-janssen commented
@liamhuber I guess all the requested changes are now implemented. So I would merge this with the master and then create a new release.

2020-11-17 16:06 UTC, liamhuber approved these changes

2020-11-17 16:07 UTC, liamhuber commented
> @liamhuber I guess all the requested changes are now implemented. So I would merge this with the master and then create a new release.

@jan-janssen before the release I would really like to see #51 fixed. This function literally doesn't do what it claims in one quadrant of the (new project, new name) map.

2020-11-17 16:08 UTC, merged

2020-11-17 16:09 UTC, jan-janssen commented
@liamhuber I agree but I do not see anybody working on it, so I am going to create a release now so we can use the creator for your pyiron pull request.